/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("animal",
        "auto",
        "all",
        "awesome",
        "arise",
        "basket",
        "bench",
        "best",
        "book",
        "camera",
        "camping",
        "candle",
        "cat",
        "chat",
        "class",
        "classic",
        "coffee",
        "cookie",
        "cruise",
        "dance",
        "daytime",
        "dine",
        "dream",
        "dusk",
        "eating",
        "emerald",
        "eerie",
        "finish",
        "flowers",
        "follow",
        "fox",
        "frame",
        "free",
        "funnel",
        "green",
        "guitar",
        "grocery",
        "glass",
        "great",
        "giggle",
        "haircut",
        "half",
        "happen",
        "honey",
        "hurry",
        "hundred",
        "ice",
        "igloo",
        "invest",
        "invite",
        "icon",
        "joke",
        "jovial",
        "journal",
        "jump",
        "join",
        "koala",
        "kind",
        "late",
        "laugh",
        "lemon",
        "letter",
        "lily",
        "marine",
        "maze",
        "melody",
        "minute",
        "moon",
        "music",
        "north",
        "nose",
        "night",
        "name",
        "never",
        "number",
        "octopus",
        "oak",
        "order",
        "open",
        "polar",
        "pack",
        "person",
        "picnic",
        "pillow",
        "pizza",
        "podcast",
        "puppy",
        "puzzle",
        "recipe",
        "release",
        "revolve",
        "rewind",
        "room",
        "run",
        "secret",
        "seed",
        "ship",
        "shirt",
        "should",
        "small",
        "skill",
        "street",
        "style",
        "sunrise",
        "taxi",
        "tidy",
        "timer",
        "tooth",
        "tourist",
        "travel",
        "truck",
        "under",
        "useful",
        "unicorn",
        "unique",
        "uplift",
        "uniform",
        "vase",
        "violin",
        "visitor",
        "vision",
        "volume",
        "view",
        "walrus",
        "wander",
        "world",
        "winter",
        "well",
        "x-ray",
        "yoga",
        "yogurt",
        "yoyo",
        "you",
        "year",
        "yummy",
        "zebra",
        "zigzag",
        "zoology",
        "zone",
        "zeal")