name: Run tests and code lint

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Also add way to start workflow manually
  workflow_dispatch:

jobs:
  # Testing app via Gradle job
  run_tests:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make gradlew executable and run tests
        run: |
          chmod +x gradlew
          ./gradlew test
          
